"""empty message

Revision ID: 6158787e1af2
Revises: 
Create Date: 2018-12-15 07:12:41.882387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6158787e1af2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('course_type', sa.String(length=2), nullable=False),
    sa.Column('has_practical', sa.Boolean(), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('course', sa.String(length=20), nullable=False),
    sa.Column('cum_credits', sa.Integer(), nullable=True),
    sa.Column('cum_grade_point', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c1', sa.Numeric(), nullable=True),
    sa.Column('c2', sa.Numeric(), nullable=True),
    sa.Column('c3', sa.Numeric(), nullable=True),
    sa.Column('c4', sa.Numeric(), nullable=True),
    sa.Column('attendance', sa.Numeric(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('grade_point', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_course')
    op.drop_table('student')
    op.drop_table('course')
    # ### end Alembic commands ###
